services:
  - type: web
    name: resident-lockdown
    runtime: node
    buildCommand: npm install && chmod -R +x node_modules/.bin && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
